version: 2
updates:
  # Check for updates to nuget packages
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: 'cron'
      cronjob: '0 8 * * MON#1'
      timezone: 'Europe/Oslo'
    labels:
      - "dependencies"
      - "nuget"
    commit-message:
      prefix: "build:"
    groups:
      # Group all non-major updates together
      minor-patch-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Check for updates to GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: 'cron'
      cronjob: '0 8 * * MON#1'
      timezone: 'Europe/Oslo'
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci:"
