name: Publish CRA Templates

on:
  push:
    tags:
      - 'cra-v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - name: Build
        run: |
          cd cra
          npm ci
          npm run build
      - name: Publish
        run: npx lerna publish from-package --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

# used this in .gitlab-ci, might be needed?
# - git update-index --assume-unchanged .npmrc